### ISSUE TITLE
Allow other PHP app installation

### ISSUE THREAD

**Issue by tareq1988** [EasyEngine/site-command#73] opened 2018-07-13 16:10 UTC
All my WordPress installations are now being transformed into [Bedrock](https://github.com/roots/bedrock/) installations, also I deploy Laravel and Lumen apps in the servers.

These can be done with EasyEngine v3.x, but needs a bit of hacking. Mainly changing the document root. Any plan on these scenarios?

**Comment by mbtamuli** [comment] 2018-07-13 16:56
Sure. We'll definitely be supporting other PHP applications in the near future, after we're able push out v4 stable. We already have support for packages, although we're building tools and the documentation to enable developers from the community to develop packages for any application. So the possibilities are endless. We might even have support for NodeJS, Python, etc.

Currently though, we're focusing on shifting to Docker so as to enable us to bring EasyEngine to more distributions than just Ubuntu and Debian. So once the v4 is out, we'll be able to plan out the roadmap better for other PHP applications.

Currently, I am closing this issue as it this is not a bug. We'll like to keep the issue tracker clean to help us fix the issues in the beta releases so we can ship v4 quicker! Thank you for your interest in EasyEngine.

**Closed by mbtamuli** 2018-07-13 16:56 UTC

**Comment by kirtangajjar** [comment] 2018-07-13 17:07
Also @tareq1988 in case you aren't aware, EasyEngine v4 will allow to extend itself with packages. Hence even if some site type is not supported by easyengine core, community will be able to develop  packages that fullfill that requirements.
