### ISSUE TITLE
Enable particular type of cache

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/site-command#289] opened 2019-01-11 10:49 UTC
Currently `--cache` enables all cache - page, object, browser etc... We need a way to enable only page cache or only browser cache.

This is helpful for development where we might not need page cache.

**Comment by mrrobot47** [comment] 2019-01-14 06:58
Closing as duplicate of https://github.com/EasyEngine/site-type-wp/issues/104

**Closed by mrrobot47** 2019-01-14 06:58 UTC
