### ISSUE TITLE
Add a domain with SSL to a WP multisite

### ISSUE THREAD

**Issue by tacensi** [EasyEngine/site-command#251] opened 2018-11-30 08:10 UTC
It is not possible now to add another domain with SSL to a multisite install.

If you have multisite with subdomains, you can use a different domain do a seconday site. Ex:

- domain1.com is the main multisite domain
- add second.domain1.com to the site network
- change second.domain1.com to domain2.com on the multisite panel.

It is not possible today to add domain2.com with ssl to the multisite network. It would be nice to have it something like `ee site update domain1.com --add-domain=domain2.com --ssl=le`

**Comment by kirtangajjar** [comment] 2018-12-04 10:59
Closing it as it is duplicate of https://github.com/EasyEngine/feature-requests/issues/23

**Closed by kirtangajjar** 2018-12-04 10:59 UTC
